# Generated by Django 2.2.9 on 2020-03-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200210_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
