# Generated by Django 3.0.2 on 2020-03-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0, verbose_name=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(default=0, verbose_name=0),
        ),
    ]
