# Generated by Django 2.2.9 on 2020-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200303_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(default=0, verbose_name=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0, verbose_name=0),
        ),
    ]
